### ISSUE TITLE
optimize loops in hfpdf

### ISSUE THREAD

**Issue by lukasheinrich** [lukasheinrich/pyhf#6]
At various stages, python loops are used in the `hfpdf` class that could feasibly be converted into more efficient numpy operations

For example:

- map-reduce of poissons (series of poisson (n,lambda)-pairs reduces by multiplication)
https://github.com/lukasheinrich/pyhf/blob/master/pyhf/__init__.py#L299
https://github.com/lukasheinrich/pyhf/blob/master/pyhf/__init__.py#L303

- histogram interpolation

right now python loop where for each bin we apply the same function .. can be batched
https://github.com/lukasheinrich/pyhf/blob/master/pyhf/__init__.py#L220

@matthewfeickert might look into this

**Comment by matthewfeickert** [comment]
@lukasheinrich Go ahead and assign this to me. I'll start with a NumPy solution. Once everything else is done we can go back and I can do timing tests for a TF solution.

As future reference for myself, in the event that line numbers change, in the `hfpdf` class I want to look at  optimize the product of the Poissons in `pdf()`, and then batch the loop in `_histosysdelta()`.

**Comment by lukasheinrich** [comment]
partly addressed by #36

**Comment by lukasheinrich** [comment]
I think this is mostly done.. we  can take a look at more optimizations later
