### ISSUE TITLE
Add Zenodo DOI

### ISSUE THREAD

**Issue by matthewfeickert** [lukasheinrich/pyhf#64]
@lukasheinrich as the repo is under your account can you [enable third-party access for Zenodo](https://help.github.com/articles/approving-oauth-apps-for-your-organization/) (if you haven't already) and then create a DOI for the project?

**Comment by lukasheinrich** [comment]
ok I created a pre-release, just to get the zenodo integration work. we should revisit this once we get close to an actual release.

**Comment by matthewfeickert** [comment]
@lukasheinrich sure. Thanks.
