### ISSUE TITLE
what's the best way to approximate continuous poisson distr

### ISSUE THREAD

**Issue by lukasheinrich** [lukasheinrich/pyhf#9]
right now we use gaussians, but maybe there is sth better for lower counts

**Comment by pablodecm** [comment]
If you only care about the pdf and cdf you can use the gamma approximation which will be exact when integers and a continuos interpolation in-between. It is what is used in RooFit.

**Comment by lukasheinrich** [comment]
thanks @pablodecm -- I was looking at that approx as well. Do you have a efficient numpy implementation of it by any chance?

**Comment by pablodecm** [comment]
This should work, if you do not mind the scipy dependency (I believe you are already using it).

````python
import numpy as np
from scipy.special import gammaln

def poisson_pdf(k, r):
    """ k is are the counts are r is the rate """
    return np.exp(k*np.log(r)-r-gammaln(k+1.))
````

**Comment by lukasheinrich** [comment]
Thanks!
